remote_theme: pages-themes/slate@v0.2.0
#>name: Grace Salo's Projects (name)
title: Grace Salo's Project
description: Check out here the projects I've created so far, and please reach out with any questions or comments!
output_dir: _config
markdown: GFM
#>url: "http://grace-salo.github.io"
include: page1.md
exclude:
- docs.txt
- '*.csv'
navbar:
  title: My Website
  left:
  - text: Home
    href: index.md
  - text: '---------'
    href: about.md
output:
  html_document:
    toc: true
    highlight: textmate
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  
