remote_theme: pages-themes/slate@v0.2.0
title: Grace Salo's Projects
description: Check out here the projects I've created so far, and reach out to gracesalo01@gmail.com with any questions or comments!
