remote_theme: pages-themes/slate@v0.2.0
#>title: Grace Salo's Projects (title)
name: Grace Salo's Projects (name)
description: Check out here the projects I've created so far, and reach out to gracesalo01@gmail.com with any questions or comments!
name: my-website
output_dir: _site
include: page1.md
exclude:
- docs.txt
- '*.csv'
navbar:
  title: My Website
  left:
  - text: Home
    href: index.md
  - text: '---------'
    href: about.md
output:
  html_document:
    toc: true
    highlight: textmate
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  
