remote_theme: pages-themes/slate@v0.2.0
name: Grace Salo's Projects (edit x2)
description: Check out here the projects I've created so far, and reach out to gracesalo01@gmail.com with any questions or comments!
[resume](/Salo_Grace_Resume.pdf)
navbar:
  title: ~~ Title ~~
  left:
  - text: Header 1
    href: slides.html
  - text: Header 2
    href: https://www.youtube.com/channel/UC5Deez8jUMnLhcf72-cHA7Q
  - text: Header 3
    href: scripts.html
  - text: Header 4
    href: plan_overview.pdf
  right:
  - text: About
    href: about.html
output:
  html_document:
    theme: flatly
    includes:
      after_body: footer.html
    lib_dir: site_libs
    self_contained: no
